### PR TITLE
Fix react-hook related warnings

### LINKED ISSUE #313: Fixing react-hooks/exhaustive-deps warnings.
**Describe the bug**
Would be great if we could fix the `react-hooks/exhaustive-deps` warnings shown in the console . 

**To Reproduce**
Just open your console after `npm I && npm start`

**Expected behavior**
The console should be clear of these warnings.

**Screenshots**
Screen Shot 2020-03-29 at 8 14 54 AM

**Additional context**
Fixing this would mean reading up `useEffect` and how their dependencies work. Here's a nice little guide https://overreacted.io/a-complete-guide-to-useeffect/

### PR DESCRIPTION
**Pull request by ssonal**
Closes #313

### CODE REVIEW

**Comment by ssonal** [comment]
All warnings now cleaned up.

File: .prettierignore [hunk 1]
```diff
@@ -0,0 +1 @@
+public/maps/
```
Comment (vinay-thallam) [inline .prettierignore]: @ssonal 

It is better to prettify the maps JSON also. There can be partial modifications to maps json in future, in that case diff does not show properly if not prettified. 

Below is the example of such commit done by one of the contributors,

https://github.com/covid19india/covid19india-react/pull/283/commits/1bb93ee02f52943ad5b88ffa2e8333a0b8be5a32

Comment (vinay-thallam) [reply .prettierignore]: Better way to speed up the pre-commit checks is to run the scripts only on the staged files instead of all files in the project using "lint-staged" configurations.

File: src/components/banner.js [hunk 2]
```diff
@@ -38,12 +46,7 @@ function Banner(props) {
     }, 10000);
     snippetChooser(0, snippets.length - 1);
     return () => clearInterval(interval);
-  }, [difference]);
-
-  const snippetChooser = (min, max) => {
-    const index = Math.random() * (max - min) + min;
-    setSnippet(snippets[Math.floor(index)]);
-  };
+  }, [difference, snippetChooser, snippets.length, start]);
```
Comment (vinay-thallam) [inline src/components/banner.js]: Is the "difference" really needed in the dep array for this effect ? Its value is not consumed in the effect.  
Also setDifference is being called which changes difference and results in effect being triggered again and so on so forth.

@jeremyphilemon  @ssonal

File: src/components/banner.js [hunk 3]
```diff
@@ -20,14 +20,22 @@ function Banner(props) {
 
   useEffect(() => {
     getSnippets();
-  }, [1]);
+  }, []);
 
   useEffect(() => {
```
Comment (vinay-thallam) [inline src/components/banner.js]: This effect is not needed. 
Instead below block of code can be put at line number 53 i.e inside axios success callback. 

`if (response.data.factoids.length > 1) {
      setSnippet(response.data.factoids[0]);
    }`

File: src/components/banner.js (hunk 2 above)
Comment (ssonal) [reply src/components/banner.js]: Makes sense. Fixed, thanks!

File: src/components/banner.js (hunk 3 above)
Comment (ssonal) [reply src/components/banner.js]: Thanks, fixed!

**Comment by jeremyphilemon** [comment]
We added a little bit more tweaks to the choropleth map in a previous patch, once you're done with resolving the conflicts we're good to go :)

File: .prettierignore (hunk 1 above)
Comment (jeremyphilemon) [reply .prettierignore]: Also it looks like I'm having trouble getting lint-staged to work? I've added the configuration but somehow when staging the files don't seem to lint, I'm not sure if I'm doing it wrong or if there's an issue. If you'd like to look into it, feel free to do so!

Comment (vinay-thallam) [reply .prettierignore]: @jeremyphilemon  Addressed it in the below PR
https://github.com/covid19india/covid19india-react/pull/364

Please review

**Comment by ssonal** [comment]
@jeremyphilemon rebased this branch on to master.

File: .prettierignore (hunk 1 above)
Comment (ssonal) [reply .prettierignore]: Dropped this commit from my PR. Best to handle it separately.
