### PR TITLE
fix(chart): fixing issue with chart legend

### LINKED ISSUE #973: Positive/Plus symbol not visible in cumulative graph
**Describe the bug**
In cumulative graph positive/plus sign is not present.

**To Reproduce**
On hovering over graph daily change values positive/plus sign is not present.
Screenshot from 2020-04-11 23-21-01

### PR DESCRIPTION
**Pull request by guptadev**
**Description of PR**
it will fix with issue with chart legend that is basically representing
the data for current status count.

**Type of PR**

- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #973

**Checklist**

- [ ] Compiles and passes lint tests
- [ ] Properly formatted
- [ ] Tested on desktop
- [ ] Tested on phone

**Screenshots**
image

image

### CODE REVIEW

**Comment by guptadev** [comment]
@shuklaayush can you please review this PR?

File: src/utils/common-functions.js [hunk 1]
```diff
@@ -115,8 +115,8 @@ export function sliceTimeseriesFromEnd(timeseries, days) {
   return timeseries.slice(timeseries.length - days);
 }
 
-const numberFormatter = new Intl.NumberFormat('en-IN');
-
 export const formatNumber = (value) => {
-  return value ? numberFormatter.format(value) : '-';
+  const numberFormatter = new Intl.NumberFormat('en-IN');
+  value = value ?? '';
+  return numberFormatter.format(value);
```
Comment (shuklaayush) [inline src/utils/common-functions.js:121]: Negligible, but maybe change this to:
```
return isNaN(value) ? '-' : numberFormatter.format(value);
```
Saves a function call

**Comment by shuklaayush** [comment]
@guptadev Thanks!
