### PR TITLE
fix:open-github-link-in-new-tab

### LINKED ISSUE #487: Github footer links should open in new tab
**Describe the bug**
Github footer links when clicked opens in same tab. Rest footer links opens in new tab.

**To Reproduce**

1. Go to https://www.covid19india.org
2. Scroll down to Footer
3. Click on 'Open Sourced on Github'
4. Notice the link is opening in same tab

**Expected behavior**
The link should open in new tab

### PR DESCRIPTION
**Pull request by Nitin96Bisht**
**Description of PR**
Open GitHub source code link in new tab.

**Type of PR**
- [x] Bugfix

**Relevant Issues**  
Fixes #487 

**Checklist**
- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -87,11 +87,15 @@ function App() {
 
         <h5>We stand with everyone fighting on the frontlines</h5>
         <div className="link">
-          <a href="https://github.com/covid19india">covid19india</a>
+          <a href="https://github.com/covid19india"
+          target="_blank"
+          rel="noopener noreferrer">covid19india</a>
```
Comment (jeremyphilemon) [inline src/App.js:92]: I see that you've also included the "noopener" and "noreferrer", could you add them to the rest of the links below too? Would be much more consistent :)

Comment (Nitin96Bisht) [reply src/App.js:92]: Yes, sure! I will do this. I will get back to you soon.

**Comment by Nitin96Bisht** [comment]
@jeremyphilemon I have added rel attribute to the rest of the links. Kindly review all of them.
