### PR TITLE
show total test data from ICMR report

### LINKED ISSUE #1013: Total Number of tests
Steps to Reproduce
* When user first navigates to the page, data for all the states is summed and displayed.
* Total number of tests is not displayed

Screen Shot 2020-04-12 at 10 15 03 AM

### PR DESCRIPTION
**Pull request by KrishnaPravin**
**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #1013 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [ ] Tested on phone

**Screenshots**

### CODE REVIEW

File: src/components/home.js [hunk 1]
```diff
@@ -40,24 +40,32 @@ function Home(props) {
...
     try {
       const [
-        response,
+        {data},
         stateDistrictWiseResponse,
         {data: statesDailyResponse},
         updateLogResponse,
-        stateTestResponse,
+        {data: stateTestData},
       ] = await Promise.all([
```
Comment (shobhitsingh29) [inline src/components/home.js:49]: use Promise.allSettled() 🤔

File: src/components/home.js [hunk 2]
```diff
@@ -40,24 +40,32 @@ function Home(props) {
...
         axios.get('https://api.covid19india.org/data.json'),
         axios.get('https://api.covid19india.org/state_district_wise.json'),
         axios.get('https://api.covid19india.org/states_daily.json'),
         axios.get('https://api.covid19india.org/updatelog/log.json'),
         axios.get('https://api.covid19india.org/state_test_data.json'),
       ]);
-      setStates(response.data.statewise);
```
Comment (shobhitsingh29) [inline src/components/home.js:55]: null checks?

File: src/components/home.js (hunk 1 above)
Comment (KrishnaPravin) [reply src/components/home.js:49]: any specific reason?

File: src/components/home.js (hunk 2 above)
Comment (KrishnaPravin) [reply src/components/home.js:55]: will try

File: src/components/home.js (hunk 1 above)
Comment (KrishnaPravin) [reply src/components/home.js:49]: If this recommendation is regarding the null check you mentioned, please create an issue. If accepted you can fix it and submit a PR.

File: src/components/home.js [hunk 3]
```diff
@@ -40,24 +40,32 @@ function Home(props) {
...
       const ts = parseStateTimeseries(statesDailyResponse);
-      ts['TT'] = preprocessTimeseries(response.data.cases_time_series); // TT -> India
+      ts['TT'] = preprocessTimeseries(data.cases_time_series); // TT -> India
       setTimeseries(ts);
-      setLastUpdated(response.data.statewise[0].lastupdatedtime);
-      setStateTestData(stateTestResponse.data.states_tested_data.reverse());
+      setLastUpdated(data.statewise[0].lastupdatedtime);
+      const testData = stateTestData.states_tested_data.reverse();
+      const totalTest = data.tested[data.tested.length - 1];
+      testData.push({
```
Comment (SensehacK) [inline src/components/home.js:62]: @KrishnaPravin Are you calculating the total tests numbers or you updated the Api repo to utilize the total numbers?

Comment (KrishnaPravin) [reply src/components/home.js:62]: Hi @SensehacK 
I did not calculate. I used `https://api.covid19india.org/data.json` this API to get the testing numbers for India. It was mentioned in the issue -- https://github.com/covid19india/covid19india-react/issues/1013#issuecomment-612651626

File: src/utils/common-functions.js [hunk 4]
```diff
@@ -117,9 +117,12 @@ export function sliceTimeseriesFromEnd(timeseries, days) {
...
 }
 
-export const formatNumber = (value) => {
+export const formatNumber = (value, shrinkNumbers) => {
   const numberFormatter = new Intl.NumberFormat('en-IN');
-  return isNaN(value) ? '-' : numberFormatter.format(value);
+  const number = isNaN(value) ? '-' : numberFormatter.format(value);
+  return shrinkNumbers && number.length > 7
+    ? `${number.replace(',', '').slice(0, -4)}K`
+    : number;
```
Comment (shuklaayush) [inline src/utils/common-functions.js]: I think it's better to use d3.format('~s') instead of implementing something ourself. Also, in my opinion, we should remove the commas if we're going with this. They'll be redundant.

Comment (KrishnaPravin) [reply src/utils/common-functions.js]: @shuklaayush done
