### PR TITLE
Set focused prop for links based on pathname

### LINKED ISSUE #289: Highlight of page incorrect when navigated directly through link
**Describe the bug**
When we directly navigate to a different page other than home page, for example, https://www.covid19india.org/faq, "Home" is highlighted instead of "FAQ".

**To Reproduce**
1. Go to https://www.covid19india.org/faq directly.
2. Observe that "Home" is highlighted instead of "FAQ".

**Expected behavior**
FAQ should be highlighted

**Screenshots**
Screen Shot 2020-03-28 at 8 27 27 PM

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

### PR DESCRIPTION
**Pull request by kousiksatish**
Fixes #289 

I am currently setting highlight based on location.pathname instead of view.
Please suggest if there is a better way to handle this.

### CODE REVIEW

File: src/components/navbar.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ function Navbar(props) {
             }}
           >
             <span
-              className={`fadeInUp ${view === "Home" ? "focused" : ""}`}
+              className={`fadeInUp ${props.location.pathname === "/" ? "focused" : ""}`}
               style={{ animationDelay: "0.2s" }}
```
Comment (vramana) [inline src/components/navbar.js]: This can be made into a method. It will cutdown the verbosity.

```
const navProps = (path, animationDelay) =>  ({
   className: `fadeInUp ${props.location.pathname === path ? "focussed": ""}`,
   state={{ animationDelay: `${animationDelay}s`}}
})
```
```
<span {...navProps('/', 0.2)} />
  Home
</span>
```

Comment (kousiksatish) [reply src/components/navbar.js]: @vramana Thanks for your review. Working on it

Comment (kousiksatish) [reply src/components/navbar.js]: @vramana Please review latest changes

**Comment by kousiksatish** [comment]
While working on this, I also thought few more things which I can work on related to navBar

- Fix ESLint errors
- Create a dictionary with ViewName, Pathname key value pair to be used across the project, including in App.js and Navbar.js . Loop through this dictionary in both places.
- In Navbar js create a new component for these links and create them by looping through the above mentioned dictionary.

Can work on this in a separate PR

**Comment by jeremyphilemon** [comment]
@kousiksatish this looks good! Regarding the enhancements, you can go ahead with them, they sound neat too! I'll close this PR and you can submit it as a new one! – don't forget to open an issue and have yourself assigned before that.

Regarding ESLint, we're planning on enforcing the style guide once we've merged a considerable good amounts of PRs anyway, but feel free to add that too if you want :)
